export enum OrderStatus {
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  AWAITING = 'AWAITING',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
  FINISHED = 'FINISHED',
  CANCELLED = 'CANCELLED',
}
